name = "An-Nahl"
number = 16
[[theme]]
from = 7
to = 8
text = "Alam itu merupakan satu kesatuan yang membuktikan kekuasaan Maha Pencipta"

[[theme]]
from = 43
to = 48
text = "Tiap-tiap umat mempunyai rasul yang diutus untuk menerangkan kebenaran"

[[theme]]
from = 49
to = 50
text = "Allah Maha Pengampun"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 68
to = 69
text = "Segi-segi pelajaran yang dapat diambil dari kehidupan alam semesta"

[[theme]]
from = 78
to = 83
text = "Tidak wajarnya sikap orang-orang musyrik menisbahkan sesuatu kepada Allah"

[[theme]]
from = 90
to = 91
text = "Perintah berbuat baik"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 98
to = 98
text = "Adab sebelum membaca Al-Qur'an"

[[theme]]
from = 125
to = 128
text = "Cara mengajak kepada kebenaran"

