name = "Al-Furqan"
number = 25
[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 63
to = 66
text = "Hamba Allah adalah yang berjalan di bumi dengan rendah hati"

[[topic]]
from = 74
to = 74
text = "Doa memohon pasangan & keturunan"

[[topic]]
from = 0
to = 0
text = "kosong"

