name = "Al-A'Raaf"
number = 7
[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 23
to = 24
text = "Doa mohon ampunan & rahmat"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 35
to = 35
text = "Rasul dari kalanganmu sendiri"

[[theme]]
from = 54
to = 55
text = "Penciptaan semesta & cara berdoa"

[[theme]]
from = 54
to = 55
text = "kosong"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 85
to = 87
text = "Kisah Nabi Syu'aib A.S"

[[theme]]
from = 174
to = 188
text = "Penghianatan orang-orang Yahudi terhadap perjanjian manusia dengan Allah"

[[theme]]
from = 204
to = 204
text = "Perintah mendengar bacaan Qur'an"

[[theme]]
from = 0
to = 0
text = "kosong"

