name = "An-Nazi'at"
number = 79
[[topic]]
from = 1
to = 14
text = "Penegasan Hari Kebangkitan Kepada Orang Musyrik yang Mengingkarinya"


[[topic]]
from = 15
to = 26
text = "Kisah Nabi Musa dan Fir'aun Sebagai Penghibur Bagi Nabi Muhammad"

[[topic]]
from = 27
to = 33
text = "Membangkitkan Manusia Adalah Mudah Bagi Allah Seperti Menciptakan Alam Semesta"

[[topic]]
from = 34
to = 46
text = "Pada Hari Kiamat Manusia Teringat Akan Perbuatannya di Dunia"

