name = "At-Tariq"
number = 86
[[topic]]
from = 1
to = 4
text = "Setiap Orang Ada yang Menjaganya"

[[topic]]
from = 5
to = 10
text = "Allah Kuasa Membangkitkan Manusia"

[[topic]]
from = 11
to = 17
text = "Al-Quran Pemisah Antara yang Haq dan yang Batil"
